name: md-docs

dep:
  ops:
    type: git
    url: "https://github.com/hatlonely/ops.git"
    version: master

env:
  default:
    NAME: "rpc-account"
  dev:
    K8S_CONTEXT: "home-k8s"
    NAMESPACE: "dev"
    RPC_ACCOUNT_SERVICE: "k8s.rpc.account.hatlonely.com"
    RPC_ARTICLE_SERVICE: "k8s.rpc.article.hatlonely.com"
    ACCOUNT_EMAIL: "{{ .account.email }}"
    ACCOUNT_PHONE: "{{ .account.phone }}"
    ACCOUNT_NAME: "{{ .account.name }}"
    ACCOUNT_PASSWORD: "{{ .account.password }}"
    ACCOUNT_BIRTHDAY: "{{ .account.birthday }}"
    ACCOUNT_GENDER: "{{ .account.gender }}"
    ACCOUNT_AVATAR: "{{ .account.avatar }}"
    MINIO_NAME: "home"
    MINIO_ENDPOINT: "https://k8s.minio.hatlonely.com"
    MINIO_USERNAME: "{{.minio.username}}"
    MINIO_PASSWORD: "{{.minio.password}}"

task:
  put-user:
    step:
      - |
        curl -XPOST -s "http://${RPC_ACCOUNT_SERVICE}/v1/getAccountByPhoneOrEmail" -d "{
            \"username\": \"${ACCOUNT_EMAIL}\"
          }" | jq -e .id || {
            curl -XPOST -s "http://${RPC_ACCOUNT_SERVICE}/v1/account" -d "{
              \"email\":\"${ACCOUNT_EMAIL}\",
              \"phone\":\"${ACCOUNT_PHONE}\",
              \"name\":\"${ACCOUNT_NAME}\",
              \"password\":\"${ACCOUNT_PASSWORD}\",
              \"birthday\":\"${ACCOUNT_BIRTHDAY}\",
              \"gender\": ${ACCOUNT_GENDER},
              \"avatar\":\"${ACCOUNT_AVATAR}\"
            }"
        }
      - |
        key=$(curl -XPOST -s "http://${RPC_ACCOUNT_SERVICE}/v1/getAccountByPhoneOrEmail" -d "{\"username\": \"${ACCOUNT_EMAIL}\"}" | jq -e -r .id)
        curl -XPOST -H "Origin:localhost" -s "http://${RPC_ARTICLE_SERVICE}/v1/author" -d "{
          \"key\": \"${key}\",
          \"name\": \"${ACCOUNT_NAME}\",
          \"avatar\": \"${ACCOUNT_AVATAR}\"
        }" && echo
  put-article:
    step:
      - |
        author_id=$(curl -XPOST -H "Origin:localhost" -s "http://${RPC_ARTICLE_SERVICE}/v1/author" -d "{
          \"key\": \"${key}\",
          \"name\": \"${ACCOUNT_NAME}\",
          \"avatar\": \"${ACCOUNT_AVATAR}\"
        }" | jq -e -r .id)
        python3 ops/tool/md2json.py -a ${author_id} -d "linux,golang,flutter,kubernetes" > "${TMP}/result.json"
      - cat "${TMP}/result.json" | while read -r line; do curl -XPOST -H "Origin:localhost" --data-binary "$line" http://${RPC_ARTICLE_SERVICE}/v1/article; echo; done
  put-image:
    step:
      - mkdir -p ${TMP}/image/thumbnail/
      - mc alias set "${MINIO_NAME}" "${MINIO_ENDPOINT}" "${MINIO_USERNAME}" "${MINIO_PASSWORD}" --api S3v4
      - mc ls ${MINIO_NAME}/article || mc mb ${MINIO_NAME}/article
      - mc cp ops/image/avatar/hatlonely.png ${MINIO_NAME}/article/avatar
      - |
        for file in `ls ops/image/thumbnail`; do
            dst_filename=${file%%.*}.png
            echo magick ops/image/thumbnail/${file} -resize 512x512 ${TMP}/image/thumbnail/${dst_filename}
            docker run --rm -v $(pwd)/ops/image/thumbnail:/src -v $(pwd)/${TMP}/image/thumbnail:/dst dpokidov/imagemagick /src/${file} -resize 512x512 /dst/${dst_filename}
            mc cp ${TMP}/image/thumbnail/${dst_filename} ${MINIO_NAME}/article/thumbnail/${dst_filename}
        done
